/**
 * Event types matching ClickHouse schema (web_events.events)
 */

export type EventType =
  | 'signup_started'
  | 'signup_completed'
  | 'signin_started'
  | 'signin_completed'
  | 'page_viewed'
  | 'checkout_started'
  | 'checkout_completed'
  | 'checkout_incomplete'
  | 'payment_method_added';

export type Source = 'Google' | 'Social' | 'Bing' | 'Direct' | 'Referral' | 'Other';
export type DeviceType = 'Desktop' | 'Mobile' | 'Tablet' | 'Android' | 'Android TV' | 'Apple TV';
export type Platform = 'iOS' | 'Android' | 'web' | 'Windows' | 'iPadOS' | 'MacOS' | 'Linux' | 'Android TV' | 'Apple TV' | 'Other';
export type LandingPage = 'homepage' | 'pricing' | 'sign up page' | 'checkout' | 'Other';
export type Plan = 'Weekly' | 'Monthly' | '3-Month' | '6-Month' | 'Yearly';
export type PaymentMethod = 'credit_card' | 'paypal' | 'google_pay';  // Credit Card, PayPal, Google Pay
export type CardType = 'visa' | 'mastercard' | 'amex';
export type Currency = 'USD' | 'EUR' | 'GBP' | 'Other';

/** ISO 3166-1 alpha-2 country code (e.g. US, UK, DE) */
export type CountryCode = string;

export interface WebEventBase {
  event_type: EventType;
  /** UUID v5; generated by app when omitted */
  event_id?: string;
  /** When event occurred (ISO 8601); server uses now() if omitted */
  event_time?: string;
  source?: Source;
  device_type?: DeviceType;
  country?: CountryCode;
  page?: LandingPage;
  platform?: Platform;
  app_version?: string;
  user_id?: string;
  os_type?: 'Mac' | 'Android' | 'Windows' | 'Linux' | 'iOS' | 'Other';
  device_id?: string;
  visitor_id?: string;
  /** SHA-512 hash of email (for PII-safe tracking) */
  email_hash?: string;
}

export interface SignUpSignInMessage {
  signup_method?: 'email' | 'google' | 'magic link';
  signin_method?: 'email' | 'google' | 'magic link';
  enter_email?: 'valid' | 'invalid';
  otp?: 'sent' | 'valid';
  magic_link?: 'sent';
  account_creation?: 'Success' | 'Failure';
}

export interface CheckoutMessage {
  plan_selected?: Plan;
  plan_updated?: Plan;
  plan_purchased?: Plan;
  plans?: Plan;
  sub_status?: string;
  amount?: number;
  currency?: Currency;
  payment_method?: PaymentMethod;
  card_type?: CardType;
  enter_email?: 'valid' | 'invalid';
}

export interface PageViewMessage {
  page_name?: string;
}

export type EventMessage = SignUpSignInMessage | CheckoutMessage | PageViewMessage | Record<string, unknown>;

export interface WebEvent extends WebEventBase {
  message?: EventMessage;
  transaction_id?: string;
}

/** Payload sent from client/server to the API */
export interface EventPayload extends WebEvent {
  /** Set by API: 'client' | 'server' */
  _source?: 'client' | 'server';
}
